Repository matchaTiff/Rutgers-Esports, pull requests merged in 2021-02, with the labels that each got.

#10 add logosdata.js
  src/data/logosdata.js
Labels: bug

#24 Updated README with information from the Google doc
  README.md
  package.json
  src/components/Discord.jsx
  src/components/data/Data.jsx
Labels: documentation

#25 change padding to match navbar
  src/components/Footer.css
Labels: polish
